### ISSUE TITLE
gitpod対応

### ISSUE THREAD

**Issue by uchicom** [uchicom/jio#1]
.gitpod.yml追加
```

tasks:
  - name: download library
    init: mvn spotless:apply verify
github:
  prebuilds:
    pullRequests: false
    addComment: false
vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-maven
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-pack
    - donjayamanne.githistory
    - github.vscode-pull-request-github
```
